# Generated by Django 6.0.1 on 2026-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
