# Generated by Django 6.0.1 on 2026-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.IntegerField(),
        ),
    ]
