# Generated by Django 6.0.1 on 2026-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_payment_time_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time_of_payment',
            field=models.PositiveBigIntegerField(),
        ),
    ]
