# Generated by Django 6.0.1 on 2026-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_payment_time_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.PositiveBigIntegerField(),
        ),
    ]
